CREATE TABLE [dbo].[Combined_FM_IM_IS_Report]
(
[Contact_ID] [int] NOT NULL,
[Product] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First_Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Institution] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Time_Spent] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Product_Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Module_Landing_Page_Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date_REMS_Question_Landing_Page] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Learner_Completion_Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REMS_Overall_Progress] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REMS_Question_Correct_Before] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REMS_Question_Correct_After] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REMS_Question_Seen_Before] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REMS_Question_Seen_After] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REMS_Question_Count_Correct] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REMS_Current_Unaware] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REMS_Proficiency] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REMS_KLP_Correct_Before] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REMS_KLP_Correct_After] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REMS_KLP_Seen_Before] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REMS_KLP_Seen_After] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Accessed] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CME_Earned] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Practice_State] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEA_Registration] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Surgical_Procedure] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Time_In_Practice] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ABIM_Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company_Institution_Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_State] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tag_Ids] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tags] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Job_Title] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Place_Of_Work_Or_Study] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Professional_Category] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Specialty] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Secondary_Specialty] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Secure_Password] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[External_NEJM_Group_CustomerID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[External_NPI_Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ABIM_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State_Of_Primary_Practice] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prescribers] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Length_Of_Time_In_Practice] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACS_License_Info] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
